-- NAEI 2024 PV group aggregation for Supabase/Postgres
-- Creates:
--   1) public."t_Group_Data" (wide year-column aggregate table, including f2024)
--   2) public.insert_24pvgroup_data() procedure (rebuilds group aggregates from naei2024pv_series/naei2024pv_values)

BEGIN;

CREATE TABLE IF NOT EXISTS public."t_Group_Data" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Group_id" integer NOT NULL,
  "Pollutant_id" bigint NOT NULL,
  f1970 numeric(43,22),
  f1971 numeric(43,22),
  f1972 numeric(43,22),
  f1973 numeric(43,22),
  f1974 numeric(43,22),
  f1975 numeric(43,22),
  f1976 numeric(43,22),
  f1977 numeric(43,22),
  f1978 numeric(43,22),
  f1979 numeric(43,22),
  f1980 numeric(43,22),
  f1981 numeric(43,22),
  f1982 numeric(43,22),
  f1983 numeric(43,22),
  f1984 numeric(43,22),
  f1985 numeric(43,22),
  f1986 numeric(43,22),
  f1987 numeric(43,22),
  f1988 numeric(43,22),
  f1989 numeric(43,22),
  f1990 numeric(43,22),
  f1991 numeric(43,22),
  f1992 numeric(43,22),
  f1993 numeric(43,22),
  f1994 numeric(43,22),
  f1995 numeric(43,22),
  f1996 numeric(43,22),
  f1997 numeric(43,22),
  f1998 numeric(43,22),
  f1999 numeric(43,22),
  f2000 numeric(43,22),
  f2001 numeric(43,22),
  f2002 numeric(43,22),
  f2003 numeric(50,29),
  f2004 numeric(43,22),
  f2005 numeric(43,22),
  f2006 numeric(43,22),
  f2007 numeric(43,22),
  f2008 numeric(43,22),
  f2009 numeric(43,22),
  f2010 numeric(43,22),
  f2011 numeric(43,22),
  f2012 numeric(43,22),
  f2013 numeric(43,22),
  f2014 numeric(43,22),
  f2015 numeric(43,22),
  f2016 numeric(43,22),
  f2017 numeric(43,22),
  f2018 numeric(43,22),
  f2019 numeric(43,22),
  f2020 numeric(43,22),
  f2021 numeric(43,22),
  f2022 numeric(43,22),
  f2023 numeric(43,22),
  f2024 numeric(43,22)
);

ALTER TABLE public."t_Group_Data"
  ADD COLUMN IF NOT EXISTS f2024 numeric(43,22);

CREATE UNIQUE INDEX IF NOT EXISTS uq_t_group_data_group_pollutant
  ON public."t_Group_Data" ("Group_id", "Pollutant_id");
CREATE INDEX IF NOT EXISTS idx_t_group_data_group_id ON public."t_Group_Data" ("Group_id");
CREATE INDEX IF NOT EXISTS idx_t_group_data_pollutant_id ON public."t_Group_Data" ("Pollutant_id");

DROP PROCEDURE IF EXISTS public.insert_24pvgroup_data();
CREATE OR REPLACE PROCEDURE public.insert_24pvgroup_data()
LANGUAGE plpgsql
AS $$
DECLARE
  g record;
BEGIN
  CREATE TEMP TABLE tmp_group_buffer (
    "Group_id" integer NOT NULL,
    "Pollutant_id" bigint NOT NULL,
    f1970 numeric(43,22),
    f1971 numeric(43,22),
    f1972 numeric(43,22),
    f1973 numeric(43,22),
    f1974 numeric(43,22),
    f1975 numeric(43,22),
    f1976 numeric(43,22),
    f1977 numeric(43,22),
    f1978 numeric(43,22),
    f1979 numeric(43,22),
    f1980 numeric(43,22),
    f1981 numeric(43,22),
    f1982 numeric(43,22),
    f1983 numeric(43,22),
    f1984 numeric(43,22),
    f1985 numeric(43,22),
    f1986 numeric(43,22),
    f1987 numeric(43,22),
    f1988 numeric(43,22),
    f1989 numeric(43,22),
    f1990 numeric(43,22),
    f1991 numeric(43,22),
    f1992 numeric(43,22),
    f1993 numeric(43,22),
    f1994 numeric(43,22),
    f1995 numeric(43,22),
    f1996 numeric(43,22),
    f1997 numeric(43,22),
    f1998 numeric(43,22),
    f1999 numeric(43,22),
    f2000 numeric(43,22),
    f2001 numeric(43,22),
    f2002 numeric(43,22),
    f2003 numeric(50,29),
    f2004 numeric(43,22),
    f2005 numeric(43,22),
    f2006 numeric(43,22),
    f2007 numeric(43,22),
    f2008 numeric(43,22),
    f2009 numeric(43,22),
    f2010 numeric(43,22),
    f2011 numeric(43,22),
    f2012 numeric(43,22),
    f2013 numeric(43,22),
    f2014 numeric(43,22),
    f2015 numeric(43,22),
    f2016 numeric(43,22),
    f2017 numeric(43,22),
    f2018 numeric(43,22),
    f2019 numeric(43,22),
    f2020 numeric(43,22),
    f2021 numeric(43,22),
    f2022 numeric(43,22),
    f2023 numeric(43,22),
    f2024 numeric(43,22),
    PRIMARY KEY ("Group_id", "Pollutant_id")
  ) ON COMMIT DROP;

  FOR g IN
    SELECT id, "NFRCode", "SourceName", "ActivityName"
    FROM public."naei_global_t_Group"
    ORDER BY id
  LOOP
    WITH
    canonical_series AS (
      SELECT
        min(s.pv_series_id) AS pv_series_id,
        s.pollutant_id,
        s.nfr_group_id,
        s.source_id,
        s.activity_id
      FROM public.naei2024pv_series s
      WHERE s.pollutant_id IS NOT NULL
      GROUP BY s.dataset_file_id, s.pollutant_id, s.nfr_group_id, s.source_id, s.activity_id
    ),
    nfr_tokens AS (
      SELECT NULLIF(btrim(x), '') AS token
      FROM regexp_split_to_table(COALESCE(g."NFRCode", ''), ';') AS x
      WHERE NULLIF(btrim(x), '') IS NOT NULL
    ),
    source_tokens AS (
      SELECT NULLIF(btrim(x), '') AS token
      FROM regexp_split_to_table(COALESCE(g."SourceName", ''), ';') AS x
      WHERE NULLIF(btrim(x), '') IS NOT NULL
    ),
    activity_tokens AS (
      SELECT NULLIF(btrim(x), '') AS token
      FROM regexp_split_to_table(COALESCE(g."ActivityName", ''), ';') AS x
      WHERE NULLIF(btrim(x), '') IS NOT NULL
    ),
    nfr_ids AS (
      SELECT DISTINCT cs.nfr_group_id AS id
      FROM canonical_series cs
      WHERE (g."NFRCode" IS NULL OR btrim(g."NFRCode") = '')
        AND cs.nfr_group_id IS NOT NULL
      UNION
      SELECT DISTINCT n.id
      FROM nfr_tokens t
      JOIN public.naei_global_t_nfrcode n
        ON n.nfr_code = t.token
      WHERE g."NFRCode" IS NOT NULL AND btrim(g."NFRCode") <> ''
    ),
    source_ids AS (
      SELECT DISTINCT cs.source_id AS id
      FROM canonical_series cs
      WHERE (g.id = 1 OR g."SourceName" IS NULL OR btrim(g."SourceName") = '')
        AND (g.id = 1 OR cs.nfr_group_id IN (SELECT id FROM nfr_ids))
        AND cs.source_id IS NOT NULL
      UNION
      SELECT DISTINCT s.id
      FROM source_tokens t
      JOIN public.naei_global_t_sourcename s
        ON s.source_name = t.token
      WHERE g."SourceName" IS NOT NULL AND btrim(g."SourceName") <> ''
    ),
    activity_ids AS (
      SELECT DISTINCT cs.activity_id AS id
      FROM canonical_series cs
      WHERE (g.id = 1 OR g."ActivityName" IS NULL OR btrim(g."ActivityName") = '')
        AND (g.id = 1 OR cs.source_id IN (SELECT id FROM source_ids))
        AND cs.activity_id IS NOT NULL
      UNION
      SELECT DISTINCT a.id
      FROM activity_tokens t
      JOIN public.naei_global_t_activityname a
        ON a.activity_name = t.token
      WHERE g."ActivityName" IS NOT NULL AND btrim(g."ActivityName") <> ''
    ),
    series_values AS (
      SELECT
        cs.pollutant_id,
        cs.nfr_group_id,
        cs.source_id,
        cs.activity_id,
        v.reporting_year,
        v.metric_value::numeric AS metric_value
      FROM canonical_series cs
      JOIN public.naei2024pv_values v
        ON v.pv_series_id = cs.pv_series_id
       AND v.metric_label = 'value'
       AND v.reporting_year BETWEEN 1970 AND 2024
    )
    INSERT INTO tmp_group_buffer (
      "Group_id",
      "Pollutant_id",
      f1970, f1971, f1972, f1973, f1974, f1975, f1976, f1977, f1978, f1979,
      f1980, f1981, f1982, f1983, f1984, f1985, f1986, f1987, f1988, f1989,
      f1990, f1991, f1992, f1993, f1994, f1995, f1996, f1997, f1998, f1999,
      f2000, f2001, f2002, f2003, f2004, f2005, f2006, f2007, f2008, f2009,
      f2010, f2011, f2012, f2013, f2014, f2015, f2016, f2017, f2018, f2019,
      f2020, f2021, f2022, f2023, f2024
    )
    SELECT
      g.id,
      sv.pollutant_id,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1970) AS f1970,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1971) AS f1971,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1972) AS f1972,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1973) AS f1973,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1974) AS f1974,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1975) AS f1975,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1976) AS f1976,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1977) AS f1977,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1978) AS f1978,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1979) AS f1979,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1980) AS f1980,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1981) AS f1981,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1982) AS f1982,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1983) AS f1983,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1984) AS f1984,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1985) AS f1985,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1986) AS f1986,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1987) AS f1987,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1988) AS f1988,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1989) AS f1989,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1990) AS f1990,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1991) AS f1991,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1992) AS f1992,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1993) AS f1993,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1994) AS f1994,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1995) AS f1995,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1996) AS f1996,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1997) AS f1997,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1998) AS f1998,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 1999) AS f1999,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2000) AS f2000,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2001) AS f2001,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2002) AS f2002,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2003) AS f2003,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2004) AS f2004,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2005) AS f2005,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2006) AS f2006,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2007) AS f2007,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2008) AS f2008,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2009) AS f2009,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2010) AS f2010,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2011) AS f2011,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2012) AS f2012,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2013) AS f2013,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2014) AS f2014,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2015) AS f2015,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2016) AS f2016,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2017) AS f2017,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2018) AS f2018,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2019) AS f2019,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2020) AS f2020,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2021) AS f2021,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2022) AS f2022,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2023) AS f2023,
      SUM(sv.metric_value) FILTER (WHERE sv.reporting_year = 2024) AS f2024
    FROM series_values sv
    WHERE sv.pollutant_id IS NOT NULL
      AND sv.nfr_group_id IN (SELECT id FROM nfr_ids)
      AND sv.source_id IN (SELECT id FROM source_ids)
      AND sv.activity_id IN (SELECT id FROM activity_ids)
    GROUP BY sv.pollutant_id;
  END LOOP;

  TRUNCATE TABLE public."t_Group_Data" RESTART IDENTITY;

  INSERT INTO public."t_Group_Data" (
    "Group_id",
    "Pollutant_id",
    f1970, f1971, f1972, f1973, f1974, f1975, f1976, f1977, f1978, f1979,
    f1980, f1981, f1982, f1983, f1984, f1985, f1986, f1987, f1988, f1989,
    f1990, f1991, f1992, f1993, f1994, f1995, f1996, f1997, f1998, f1999,
    f2000, f2001, f2002, f2003, f2004, f2005, f2006, f2007, f2008, f2009,
    f2010, f2011, f2012, f2013, f2014, f2015, f2016, f2017, f2018, f2019,
    f2020, f2021, f2022, f2023, f2024
  )
  SELECT
    "Group_id",
    "Pollutant_id",
    f1970, f1971, f1972, f1973, f1974, f1975, f1976, f1977, f1978, f1979,
    f1980, f1981, f1982, f1983, f1984, f1985, f1986, f1987, f1988, f1989,
    f1990, f1991, f1992, f1993, f1994, f1995, f1996, f1997, f1998, f1999,
    f2000, f2001, f2002, f2003, f2004, f2005, f2006, f2007, f2008, f2009,
    f2010, f2011, f2012, f2013, f2014, f2015, f2016, f2017, f2018, f2019,
    f2020, f2021, f2022, f2023, f2024
  FROM tmp_group_buffer
  ORDER BY "Group_id", "Pollutant_id";
END;
$$;

-- Compatibility alias for existing callers using the old MySQL-style name.
DROP PROCEDURE IF EXISTS public.insert_23dsgroup_data();
CREATE OR REPLACE PROCEDURE public.insert_23dsgroup_data()
LANGUAGE plpgsql
AS $$
BEGIN
  CALL public.insert_24pvgroup_data();
END;
$$;

-- Read-only exposure for anon/authenticated; full manage for service_role.
ALTER TABLE public."t_Group_Data" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."t_Group_Data" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS t_group_data_read ON public."t_Group_Data";
CREATE POLICY t_group_data_read
ON public."t_Group_Data"
FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS t_group_data_manage_service ON public."t_Group_Data";
CREATE POLICY t_group_data_manage_service
ON public."t_Group_Data"
AS PERMISSIVE
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

REVOKE ALL ON TABLE public."t_Group_Data" FROM anon, authenticated;
GRANT SELECT ON TABLE public."t_Group_Data" TO anon, authenticated;
GRANT ALL ON TABLE public."t_Group_Data" TO service_role;

DO $$
BEGIN
  IF to_regclass('public."t_Group_Data_id_seq"') IS NOT NULL THEN
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE public."t_Group_Data_id_seq" TO service_role';
  END IF;
END
$$;

GRANT EXECUTE ON PROCEDURE public.insert_24pvgroup_data() TO service_role;
GRANT EXECUTE ON PROCEDURE public.insert_23dsgroup_data() TO service_role;

COMMIT;
